In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("loan_approval_dataset.csv")
data

loan_id   no_of_dependents      education  self_employed   income_annum  \
0           1                  2       Graduate             No        9600000   
1           2                  0   Not Graduate            Yes        4100000   
2           3                  3       Graduate             No        9100000   
3           4                  3       Graduate             No        8200000   
4           5                  5   Not Graduate            Yes        9800000   
...       ...                ...            ...            ...            ...   
4264     4265                  5       Graduate            Yes        1000000   
4265     4266                  0   Not Graduate            Yes        3300000   
4266     4267                  2   Not Graduate             No        6500000   
4267     4268                  1   Not Graduate             No        4100000   
4268     4269                  1       Graduate             No        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000   
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000   
1                      2200000               8800000            3300000   
2                      4500000              33300000           12800000   
3                      3300000              23300000            7900000   
4                      8200000              29400000            5000000   
...                        ...                   ...                ...   
4264                    500000               3300000             800000   
4265                   2900000              11000000            1900000   
4266                  12400000              18100000            7300000   
4267                    700000              14100000            5800000   
4268                  11800000              35700000           12000000   

      loan_status  
0        Approved  
1        Rejected  
2        Rejected  
3        Rejected  
4        Rejected  
...           ...  
4264     Rejected  
4265     Approved  
4266     Rejected  
4267     Approved  
4268     Approved  

[4269 rows x 13 columns]

In [3]:
data.columns


Index(['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
e=LabelEncoder()
data[" loan_status"]=e.fit_transform(data[" loan_status"])

In [6]:
data

loan_id   no_of_dependents      education  self_employed   income_annum  \
0           1                  2       Graduate             No        9600000   
1           2                  0   Not Graduate            Yes        4100000   
2           3                  3       Graduate             No        9100000   
3           4                  3       Graduate             No        8200000   
4           5                  5   Not Graduate            Yes        9800000   
...       ...                ...            ...            ...            ...   
4264     4265                  5       Graduate            Yes        1000000   
4265     4266                  0   Not Graduate            Yes        3300000   
4266     4267                  2   Not Graduate             No        6500000   
4267     4268                  1   Not Graduate             No        4100000   
4268     4269                  1       Graduate             No        9200000   

       loan_amount   loan_term   cibil_score   residential_assets_value  \
0         29900000          12           778                    2400000   
1         12200000           8           417                    2700000   
2         29700000          20           506                    7100000   
3         30700000           8           467                   18200000   
4         24200000          20           382                   12400000   
...            ...         ...           ...                        ...   
4264       2300000          12           317                    2800000   
4265      11300000          20           559                    4200000   
4266      23900000          18           457                    1200000   
4267      12800000           8           780                    8200000   
4268      29700000          10           607                   17800000   

       commercial_assets_value   luxury_assets_value   bank_asset_value  \
0                     17600000              22700000            8000000   
1                      2200000               8800000            3300000   
2                      4500000              33300000           12800000   
3                      3300000              23300000            7900000   
4                      8200000              29400000            5000000   
...                        ...                   ...                ...   
4264                    500000               3300000             800000   
4265                   2900000              11000000            1900000   
4266                  12400000              18100000            7300000   
4267                    700000              14100000            5800000   
4268                  11800000              35700000           12000000   

       loan_status  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
4264             1  
4265             0  
4266             1  
4267             0  
4268             0  

[4269 rows x 13 columns]

In [7]:
data[" education"]=e.fit_transform(data[" education"])

In [8]:
data[" self_employed"]=e.fit_transform(data[" self_employed"])

In [9]:
x=data[[' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value']]
y=data[" loan_status"]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [12]:
from sklearn.tree import DecisionTreeClassifier

In [13]:
model=DecisionTreeClassifier()

In [14]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
pred=model.predict(x_test)

In [16]:
pred

array([1, 0, 1, ..., 0, 1, 0])

In [17]:
from sklearn.metrics import accuracy_score

In [18]:
score=accuracy_score(y_test,pred)

In [19]:
score

0.9836065573770492

In [20]:
values=[4,1,0,600000,1500000,20,315,2000000]
columns=[' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value']
index=[1,2,3,4,5,6,7,8]

In [21]:
input_data=pd.DataFrame([values],columns=columns)

In [22]:
val=model.predict(input_data)

In [23]:
if val==1:
    print("Yes")
else:
    print("No")

Yes


In [24]:
model.predict([[4,1,0,600000,1500000,20,315,2000000]])

c:\Users\lavan\anaconda\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [25]:
# Save the model
import pickle 
with open('loan_approval_decision_tree.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)

In [26]:
with open('loan_approval_model.pkl', 'wb') as model_file:
    pickle.dump({'model': model, 'encoder': e}, model_file)

In [27]:
import joblib

# Save the model and encoder
joblib.dump(model, 'loan_approval_model.joblib')
joblib.dump(e, 'label_encoder.joblib')


['label_encoder.joblib']

In [28]:
from joblib import dump, load

# Save the model to a file
dump(model, 'loan_approval_model.joblib')

# Load the model from the file
loaded_model = load('loan_approval_model.joblib')


In [29]:
loaded_model.predict([[4,1,0,600000,1500000,20,315,2000000]])

c:\Users\lavan\anaconda\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1])

In [30]:
import joblib

print("Joblib version:", joblib.__version__)


Joblib version: 1.3.2


In [31]:
pip install --upgrade joblib


Note: you may need to restart the kernel to use updated packages.


In [33]:
import joblib

print("Joblib version:", joblib.__version__)

Joblib version: 1.3.2


In [35]:
import pickle 
with open('loan.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)


In [1]:
import pickle

# Open the file in binary read mode ('rb')
with open("loan_approval_model.pkl", 'rb') as file:
    # Load the pickled model
    loan_model = pickle.load(file)
